name: BannerMaker
main: tw.kid7.BannerMaker.BannerMaker
version: 1.2
author: KID
softdepend: [Vault]
commands:
    BannerMaker:
        description: BannerMaker
        usage: /<command>
        aliases: [bm]
        permission: BannerMaker.use
        permission-message: Lacking permission <permission>
permissions:
    BannerMaker.*:
        description: Whole permission of BannerMaker
        default: op
        children:
            BannerMaker.use: true
            BannerMaker.getBanner: true
            BannerMaker.reload: true
    BannerMaker.use:
        description: Permission of using BannerMaker
        default: op
    BannerMaker.getBanner:
        description: Permission to get banners from BannerMaker
        default: op
    BannerMaker.getBanner.free:
        description: Bypass fee of get Banner
        default: op
    BannerMaker.reload:
        description: Permission to reload all config
        default: op
